### Simple: single/rules-that-return-single-item.drl.xlsx
POST http://localhost:8080/v1/drools/simple-object
Content-Type: application/json

{
  "id": 1,
  "name": "name1"
}

### DRL: drl/rules.drl
POST http://localhost:8080/v1/drools/simple-object-from-drl
Content-Type: application/json

{
  "id": 1,
  "name": "name1"
}

### Simple w/ subObject: single/rules-that-return-single-item-with-subObject.drl.xlsx
POST http://localhost:8080/v1/drools/object-with-sub-object
Content-Type: application/json

{
  "id": 1,
  "name": "name1"
}

### Simple w/ subObject: single/rules-that-return-single-item-with-subObject.drl.xlsx
POST http://localhost:8080/v1/drools/object-with-sub-object
Content-Type: application/json

{
  "id": 2,
  "name": "name1"
}

### List: list/rules-that-return-list.drl.xlsx
POST http://localhost:8080/v1/drools/object-list
Content-Type: application/json

{
  "id": 1,
  "name": "name1"
}

### List: list/rules-that-return-list.drl.xlsx
POST http://localhost:8080/v1/drools/object-list
Content-Type: application/json

{
  "id": 2,
  "name": "name2"
}